gh-4 Implement standard install rules. - Build will require standard hadoop lib location, and will look for include  header file in tarballed location.
Signed-off-by: Rodrigo Pastrana <Rodrigo.Pastrana@lexisnexis.com>

diff --git a/hdfspipe.in b/hdfspipe.in
--- a/hdfspipe.in
+++ b/hdfspipe.in
@@ -17,20 +17,35 @@
 #    along with All rights reserved. This program is free software: you can redistribute program.  If not, see <http://www.gnu.org/licenses/>.
 #############################################
 
+#DO NOT CHANGE THIS FILE, CONFIGURATION CHANGES CAN BE DONE HERE:
+# @HPCC_CONF_DIR@/@HDFSCONN_CONF_FILE@
+
 source @HPCC_ETC_DIR@/init.d/hpcc_common
 set_environmentvars
 
-source @HPCC_CONF_DIR@/@HDFSCONN_CONF_FILE@ 
+source @HPCC_CONF_DIR@/@HDFSCONN_CONF_FILE@
 
-CLASSPATH=$CLASSPATH:$HADOOP_LOCATION/conf
+CLASSPATH=$CLASSPATH:$HADOOP_CONF_DIR
 
-for f in $HADOOP_LOCATION/*.jar ; do
+for f in $HADOOP_SHARE_DIR/*.jar ; do
     CLASSPATH=$CLASSPATH:$f
 done
 
-for f in $HADOOP_LOCATION/lib/*.jar ; do
+for f in $HADOOP_SHARE_DIR/lib/*.jar ; do
     CLASSPATH=$CLASSPATH:$f
 done
+
+if [ -n "$TARBALL_HADOOP_LOCATION"  ]; then
+    CLASSPATH=$CLASSPATH:$TARBALL_HADOOP_LOCATION/conf
+
+    for f in $TARBALL_HADOOP_LOCATION/*.jar ; do
+        CLASSPATH=$CLASSPATH:$f
+    done
+
+    for f in $TARBALL_HADOOP_LOCATION/lib/*.jar ; do
+        CLASSPATH=$CLASSPATH:$f
+    done
+fi
 
 export CLASSPATH=$CLASSPATH
 
@@ -55,6 +70,7 @@ done;
 LOGS_LOCATION=$log
 HDFSCONNLOGLOC=$LOGS_LOCATION/mydataconnectors
 LOG=$HDFSCONNLOGLOC/HDFSCONNECTOR.$nodeid.$PID.log
+PIPERRLOG=$HDFSCONNLOGLOC/HPCC-FIFO.err.$PID
 
 if [ -e $HDFSCONNLOGLOC ]
   then
@@ -73,16 +89,16 @@ h2hstatus=0;
 
 if [ "$1" = "" ];
 then
-    echo "Running without input params" >> $LOG
-    h2hstatus=1;
+	echo "Running without input params" >> $LOG
+	exit 1;
 elif [ $1 = "-mf" ];
 then
-    /opt/HPCCSystems/bin/hdfsconnector "${@}"      2>> $LOG;
+    @HDFSCONN_EXE_PATH@ "${@}"      2>> $LOG;
     h2hstatus=$?;
     h2hpid=$!;
 elif [ $1 = "-si" ];
 then
-    /opt/HPCCSystems/bin/hdfsconnector  "${@}"      2>> $LOG;
+    @HDFSCONN_EXE_PATH@  "${@}"      2>> $LOG;
     h2hstatus=$?
     h2hpid=$!;
 elif [ $1 = "-so" ];
@@ -103,25 +119,25 @@ then
 
     echo "calling hdfsconnector..."         >> $LOG
 
-    /opt/HPCCSystems/bin/hdfsconnector "${@}" -pipepath $HPCCTMPFILE  	2>> $LOG
+    @HDFSCONN_EXE_PATH@ "${@}" -pipepath $HPCCTMPFILE  	2>> $LOG
     h2hpid=$!;
     h2hstatus=$?;
 elif [ $1 = "-sop" ];
 then
     pipepath=/tmp/HPCCPIPE_$nodeid;
-    mkfifo $pipepath 2> /tmp/HPCC-FIFO.err.$PID;
-    chmod 777 $pipepath 2> /tmp/HPCC-FIFO.err.$PID;
+    mkfifo $pipepath 2> $PIPERRLOG;
+    chmod 777 $pipepath 2> $PIPERRLOG;
 
     echo "mkfifo $pipepath setup ..."           >> $LOG
 
-    if test ! -s "/tmp/HPCC-FIFO.err.$PID"
+    if test ! -s "$PIPERRLOG"
     then
-        rm -f /tmp/HPCC-FIFO.err.$PID 2> /dev/null
+        rm -f $PIPERRLOG 2> /dev/null
     else
-        echo "Error while setting up named pipe, registered in file: /tmp/HPCC-FIFO.err.$PID " >> $LOG
+        echo "  WARNING (hdfsconnector mkfifo) error registered in file: $PIPERRLOG " >> $LOG
         exit 1
     fi
-    /opt/HPCCSystems/bin/hdfsconnector  "${@}" -pipepath $pipepath	2>> $LOG &
+    @HDFSCONN_EXE_PATH@  "${@}" -pipepath $pipepath	2>> $LOG &
 
     h2hpid=$!;
 
