gh-10 Named pipe must be closed if pipeout failed. Includes changes from code review.
Cherry-pick changes from https://github.com/hpcc-systems/h2h/pull/12/commits

Signed-off-by: Rodrigo Pastrana <Rodrigo.Pastrana@lexisnexis.com>

diff --git a/hdfspipe.in b/hdfspipe.in
--- a/hdfspipe.in
+++ b/hdfspipe.in
@@ -110,7 +110,7 @@ elif [ $1 = "-sop" ];
 then
     pipepath=/tmp/HPCCPIPE_$nodeid;
     mkfifo $pipepath 2> /tmp/HPCC-FIFO.err.$PID;
-    chmod 666 $pipepath 2> /tmp/HPCC-FIFO.err.$PID;
+    chmod 777 $pipepath 2> /tmp/HPCC-FIFO.err.$PID;
 
     echo "mkfifo $pipepath setup ..."           >> $LOG
 
@@ -118,7 +118,8 @@ then
     then
         rm -f /tmp/HPCC-FIFO.err.$PID 2> /dev/null
     else
-        echo "  WARNING (hdfsconnector mkfifo) error registered in file: /tmp/HPCC-FIFO.err.$PID " >> $LOG
+        echo "Error while setting up named pipe, registered in file: /tmp/HPCC-FIFO.err.$PID " >> $LOG
+        exit 1
     fi
     /opt/HPCCSystems/bin/hdfsconnector  "${@}" -pipepath $pipepath	2>> $LOG &
 
@@ -127,10 +128,20 @@ then
     echo h2h pid: ${h2hpid} >> $LOG
     echo "redirecting stdin to named pipe ... "    >> $LOG
 
-	cat < /dev/stdin > "$pipepath" &
-    ls -l "$HPCCTMPFILE"                        >> $LOG
+    cat < /dev/stdin > "$pipepath" &
+    ls -l "$pipepath"                               >> $LOG
+    echo "Waiting on hdfsconnector PID ${h2hpid}"   >> $LOG
     wait ${h2hpid};
     h2hstatus=$?;
+    echo "Finished waiting on hdfsconnector exit status: ${h2hstatus}" >> $LOG
+
+    if [ ${h2hstatus} -ne 0 ];
+    then
+        echo "Closing pipe due to hdfsconnector error" >> $LOG
+        exec  <&- 2>> $LOG
+        exec $pipepath <&- 2>> $LOG
+    fi
+    rm -f $pipepath 2>> $LOG
 else
     echo "Error: check your params."             >> $LOG;
     h2hstatus=1;
